@startuml
title ESP32 GPS Client Operational State Flow

Start
: NVS Int;
: Wi-Fi Init;
: SNTP Sync;
while (check_time);
    if (Operating Window?) then (yes)
        if (First Quarter?) then (yes)
            : Send Transimision Data;
            : polling sleep;
        else (no)
            : Three Quarter Light Sleep;
            : Light Sleep;
        endif
    elseif (Pre Operating Window?) then (yes)
        : Pre Window Light Sleep;
        : Light Sleep;
    else (no)
        : Deep Sleep;
    endif
    switch (sleep method?)
    case (deep sleep)
        : Enter Deep Sleep \n Time until next (START_HOUT - WAKEUP);
        stop
    case (light sleep)
        : Enter Light Sleep \n (60-time_min)*60;
    case (polling sleep)
        : Enter Polling Light Sleep \n (POLLING_INTERVAL_SEC);
    endswitch
    :VTaskDelay;

endwhile
-[hidden]->
detach
@enduml